services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: tajji_auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  axonserver:
    image: axoniq/axonserver
    container_name: axonserver
    environment:
      AXONSERVER_TOKEN: f1d02e40-94a2-475a-ab34-b5bd0c32ad55
    ports:
      - "8124:8124"
      - "8024:8024"
    volumes:
      - axonserver_data:/data

  minio:
    image: 'bitnami/minio:2024.10.2'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  redis_data:
  axonserver_data:
  minio_data:
